config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/search/add_alert', to: 'searches#add_alert', as: 'add_alert'
  get '/search/:search_word', to: 'searches#show', as: 'search'
  get '/user', to: 'users#index', as: 'user'
  delete '/user/:id', to: 'users#destroy', as: 'destroy_user'
  get 'welcome/index'
  get '/profile', to: 'profiles#index', as: 'user_profile'
  delete '/profile/:id', to: 'profiles#destroy', as: 'delete_user_profile'
  root 'welcome#index'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @alerts = Alert.where(:user_id => current_user.id)
  end

  def destroy
    alert = Alert.find(params[:id])
    alert.destroy
    flash[:success] = 'Alerta removido com sucesso!'
    redirect_to user_profile_path
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/index.html.erb
<div class="wrapper">
  <div id="search_content" class="medium_wrapper wrapper_padding clearfix">
    <header><h1>Perfil</h1></header>
    <hr>
    <br>
    <div class="col-small"> 
      <%= gravatar_for(current_user, 'gravatar-big')%>
      <h3><%= current_user.name %></h3>
    </div>  

    <div class="col-big">
      <h3>Alertas Cadastrados</h3>
      <table id="alerts" class="display responsive no-wrap">
        <thead>
            <tr>
              <th>Pesquisa</th>
              <th>Preço</th>
              <th>Ações</th>
            </tr>
        </thead>
        <tbody>
          <% @alerts.each do |a| %>
            <tr>
              <td><%= a.search_word %></td>
              <td><%= currency_format(a.price) %></td>
              <td><%= link_to 'Deletar', delete_user_profile_path(a.id), :method => 'delete' %>
            </tr>  
          <% end %>       
        </tbody>
      </table>
    </div>
  </div>
</div>  

<% content_for :js do %>


 $(document).ready(function () {
  var oTable = $('#alerts').dataTable({
      responsive: true,
      "oLanguage": {
              "sProcessing": "Aguarde enquanto os dados são carregados ...",
              "sLengthMenu": "Mostrar _MENU_ registros por pagina",
              "sZeroRecords": "Nenhum registro correspondente ao criterio encontrado",
              "sInfoEmtpy": "Exibindo 0 a 0 de 0 registros",
              "sInfo": "Exibindo de _START_ a _END_ de _TOTAL_ registros",
              "sInfoFiltered": "",
              "sSearch": "Procurar",
      "oPaginate": {
                  "sFirst": "Primeiro",
                  "sPrevious": "Anterior",
                  "sNext": "Próximo",
                  "sLast": "Último"
              }
          }
    });
  });
<% end %>