config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/search/add_alert', to: 'searches#add_alert', as: 'add_alert'
  get '/search/:search_word', to: 'searches#show', as: 'search'
  get '/user', to: 'users#index', as: 'user'
  delete '/user/:id', to: 'users#destroy', as: 'destroy_user'
  get 'welcome/index'
  get '/profile', to: 'profiles#index', as: 'user_profile'
  delete '/profile/:id', to: 'profiles#destroy', as: 'delete_user_profile'
  root 'welcome#index'
end

app/models/search.rb
class Search < ActiveRecord::Base
  require 'rubygems'
  require 'mechanize'

  @search_word
  @found_products

  def Search.load_products_links link, product_link_tag
    agent = Mechanize.new
    page = agent.get(link)

    agent.shutdown()

    page.search(product_link_tag)
  end

  def Search.load_product_page_html link
    agent = Mechanize.new
    page = agent.get(link)

    agent.shutdown()

    page
  end

  def Search.parse_product_html page, site, product_link
    product = Product.new

    product.status = true
    product.search_word = @search_word

    product.price = page.search(site.price_tag).to_s
                                               .delete("^0-9,")
                                               .gsub(',','.')
                                               .to_d
    product.link = product_link
    product.image_link = page.search(site.image_tag).to_s
    product.site_id = site.id
    product.description = page.search(site.description_tag).to_s
    product.category = page.search(site.category_tag).to_s
                                                     .strip
                                                     .split.map(&:capitalize).join(' ')
    if product.category == ""
      product.category = "N/A"
    end
    product
  end

  def Search.search_products search_word
    @search_word = search_word
    sites = Site.where(:status => true)
    threads = Array.new
    product_threads = Array.new
    @found_products = Array.new

    sites.each do |s|
      threads << Thread.new {

        #Load link for each product
        links = Array.new
        links = load_products_links(s.link + @search_word, s.product_link_tag)

        pages = Array.new
        links.each { |l|

          product_threads << Thread.new {
            page = load_product_page_html(l.to_s)

            @found_products << parse_product_html(page, s, l.to_s)
          }
        }

        product_threads.each {|x| x.join}

      }
    end

    threads.each {|x| x.join}

    #Remove products with price less than or equals zero
    @found_products.reject! { |x| x.price <= 0.0 }

    Thread.new { save_data }

    @found_products.sort_by{|e| e[:price]}

  end

  def Search.save_data
    Thread.new{

      Search.where(search_word: @search_word).first_or_create

      Product.transaction do
      Product.where("search_word = ?", @search_word)
             .update_all(:status => false)
      @found_products.each(&:save)

      end
    }
  end

  def Search.update_prices
    searches = Search.all

    searches.each do |s|
      Thread.new { search_products s.search_word }
      #debugger
      sleep 15
    end

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
    @search_word = params[:search_word].downcase
    search = Search.find_by(search_word: @search_word)

    @results = nil

    if(search.nil?)
      @results = Search.search_products @search_word
    else
      search.count += 1;
      search.save
      @results = Product.where(search_word: @search_word, status: true).order(price: :asc).includes(:site)
    end

    @price_history = Product.price_history @search_word

    dates = []
    prices = []

    @price_history.reverse.each do |p|
      dates <<  l(p.created_at, format: '%d %b')
      prices << p.price
    end

    @chart = LazyHighCharts::HighChart.new('area') do |f|
      f.title(:text => "Histórico de Preço (R$)")
      f.xAxis(:categories => dates)
      f.series(:name => "Preço", :yAxis => 0, :data => prices)
      f.chart({:defaultSeriesType=>"area"})
    end

  end

  def add_alert
    user_id = current_user.id
    search_word = params[:search_word].downcase
    price = params[:price]
    category = params[:category]

    alert = Alert.create_alert user_id, search_word, category, price
    flash[:success] = "Alerta salvo com sucesso!"
    redirect_to user_profile_path
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/show.html.erb
<div class="wrapper">
  <div id="search_content" class="medium_wrapper wrapper_padding clearfix">
    <header><h1>Resultados da Pesquisa</h1></header>
    <hr>
    <br>
    <div class="col-small">
      <h4>Adicionar Alerta de Preço</h4>
      <% if user_signed_in? %>
        <%= form_tag(add_alert_path,  :id => 'add_alert', :method => 'get' ) do %>
          <%= hidden_field_tag 'search_word', @search_word %>
          <div class="input-group">
            <input type="text" id="price" name="price" placeholder="R$ " onkeypress="return isNumberKey(event)" required/>
            <span style="margin-left:10px">
              <button type="submit" >
                   <span class="glyphicon glyphicon-plus"></span>
              </button>
            </span>
          </div>
        <% end %>
      <% else %>
        <li><%= link_to "Faça login para adicionar um alerta.", new_user_session_path %></li>
      <% end %>
      <h4>Categorias</h4>
      <div id="categories"></div>
    </div>

    <div class="col-big">
      <%= high_chart("price_history", @chart) do |c|%>
        <%= raw "options.tooltip.formatter = function() {
          return '<b>Preço</b>: R$'+ parseFloat(this.y).toFixed(2);
        }" %>
      <% end %>
      <table id="resultado" class="display responsive no-wrap">
        <thead>
            <tr>
              <th>Imagem</th>
              <th>Loja</th>
              <th style="display:none">Categoria</th>
              <th>Produto</th>
              <th>Preço</th>
            </tr>
        </thead>
        <tbody>
          <% @results.each do |r| %>
            <tr>
              <td><%= image_tag(r.image_link, :class => "productImg") %></td>
              <td class="nowrap">
                <%= image_tag(r.site.logo, :class => "site-logo") %>
                <%= rating_for r.site, "id" , :disable_after_rate => false %>
              </td>
              <td style="display:none"><%= r.category %></td>
              <td><%= link_to r.description.first(75) + '...', r.link, :target => '_blank' %></td>
              <td><%= currency_format(r.price) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% content_for :js do %>

function isNumberKey(evt){
            var charCode = (evt.which) ? evt.which : event.keyCode
            if (charCode > 31 && (charCode < 48 || charCode > 57))
                return false;
            return true;
    }

 $(document).ready(function () {
  var oTable = $('#resultado').dataTable({
      responsive: true,
      "oLanguage": {
              "sProcessing": "Aguarde enquanto os dados são carregados ...",
              "sLengthMenu": "Mostrar _MENU_ registros por pagina",
              "sZeroRecords": "Nenhum registro correspondente ao criterio encontrado",
              "sInfoEmtpy": "Exibindo 0 a 0 de 0 registros",
              "sInfo": "Exibindo de _START_ a _END_ de _TOTAL_ registros",
              "sInfoFiltered": "",
              "sSearch": "Procurar",
      "oPaginate": {
                  "sFirst": "Primeiro",
                  "sPrevious": "Anterior",
                  "sNext": "Próximo",
                  "sLast": "Último"
              }
          }
  });

  // Populate values
    var $rows = oTable.fnGetNodes();
    var values = {};
    var colnums = [3];

    for (var col = 0, n = colnums.length; col < n; col++) {

        var colnum = colnums[col];
        if (typeof values[colnum] === "undefined") values[colnum] = {};

        // Create Unique List of Values
        $('td:nth-child(' + colnum + ')', $rows).each(function () {
            values[colnum][$(this).text()] = 1;
        });

        // Create Checkboxes
        var labels = [];
        $.each(values[colnum], function (key, count) {
            var $checkbox = $('<input />', {
                'class': 'filter-column filter-column-' + colnum,
                    'type': 'checkbox',
                    'value': key
            });
            var $label = $('<label></label>', {
                'class': 'filter-container'
            }).append($checkbox).append(' ' + key);
            $checkbox.on('click', function () {
                oTable.fnDraw();
            }).data('colnum', colnum);
            labels.push($label.get(0));
        });
        var $sorted_containers = $(labels).sort(function (a, b) {
            return $(a).text().toLowerCase() > $(b).text().toLowerCase();
        });
        $('#categories').prepend($sorted_containers);
        $sorted_containers.wrapAll($('<div></div>', {
            'class': 'checkbox-group checkbox-group-column-' + colnum
        }));
    }

    $.fn.dataTableExt.afnFiltering.push(function (oSettings, aData, iDataIndex) {
        var checked = [];
        $('.filter-column').each(function () {
            var $this = $(this);
            if ($this.is(':checked')) checked.push($this);
        });

        if (checked.length) {
            var returnValue = false;
            $.each(checked, function (i, $obj) {
                if (aData[$obj.data('colnum') - 1] == $obj.val()) {
                    returnValue = true;
                    return false; // exit loop early
                }
            });

            return returnValue;
        }

        if (!checked.length) return true;
        return false;
    });


});
<% end %>