config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/search/add_alert', to: 'searches#add_alert', as: 'add_alert'
  get '/search/:search_word', to: 'searches#show', as: 'search'
  get '/user', to: 'users#index', as: 'user'
  delete '/user/:id', to: 'users#destroy', as: 'destroy_user'
  get 'welcome/index'
  get '/profile', to: 'profiles#index', as: 'user_profile'
  delete '/profile/:id', to: 'profiles#destroy', as: 'delete_user_profile'
  root 'welcome#index'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true

  def Alert.send_mail product, user

    AlertMailer.price_alert(user, product).deliver_now
  end

  def Alert.check_prices
    alerts = Alert.where(:email_sent => false)

    alerts.each do |a|

      product = Product.where(:search_word => a.search_word, :status => true).order('price asc').first

      if(a.price > product.price)
        user = User.find(a.user_id)
        send_mail product, user
        a.email_sent = true
        a.save
      end 

    end
  end

  def Alert.remove_alerts
    alerts = Alert.where(:email_sent => true)

    Alert.transaction do 
      alerts.each(&:delete)
    end

  end

  def Alert.create_alert user_id, search_word, category, price
    alert = Alert.new


    alert.search_word = search_word
    alert.user_id = user_id
    alert.category = category
    alert.price = price.to_d
    alert.email_sent = false

    alert.save

    alert
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :site 

  def name
    self.description
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :site
  validates :site, presence: true

  def Product.price_history search_word
    Product.select("min(price) price, date(created_at) created_at").group("date(created_at)").where("search_word = ? AND date(created_at) <= date(curdate())", search_word).order(:created_at => 'desc').take(7)
  end

  def Product.last_searched
   searches =  Search.all.order(:updated_at => 'desc').limit(3)

   products = []
   searches.each do |s|
    products << Product.where("search_word = ? and status = 1", s.search_word).order(:price => 'asc').first
   end

   products
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/search.rb
class Search < ActiveRecord::Base
  require 'rubygems'
  require 'mechanize'

  @search_word
  @found_products

  def Search.load_products_links link, product_link_tag
    agent = Mechanize.new
    page = agent.get(link)

    agent.shutdown()

    page.search(product_link_tag)
  end

  def Search.load_product_page_html link
    agent = Mechanize.new
    page = agent.get(link)

    agent.shutdown()

    page
  end

  def Search.parse_product_html page, site, product_link
    product = Product.new

    product.status = true
    product.search_word = @search_word

    product.price = page.search(site.price_tag).to_s
                                               .delete("^0-9,")
                                               .gsub(',','.')
                                               .to_d
    product.link = product_link
    product.image_link = page.search(site.image_tag).to_s
    product.site_id = site.id
    product.description = page.search(site.description_tag).to_s
    product.category = page.search(site.category_tag).to_s
                                                     .strip
                                                     .split.map(&:capitalize).join(' ')
    if product.category == ""
      product.category = "N/A"
    end
    product
  end

  def Search.search_products search_word
    @search_word = search_word
    sites = Site.where(:status => true)
    threads = Array.new
    product_threads = Array.new
    @found_products = Array.new

    sites.each do |s|
      threads << Thread.new {

        #Load link for each product
        links = Array.new
        links = load_products_links(s.link + @search_word, s.product_link_tag)

        pages = Array.new
        links.each { |l|

          product_threads << Thread.new {
            page = load_product_page_html(l.to_s)

            @found_products << parse_product_html(page, s, l.to_s)
          }
        }

        product_threads.each {|x| x.join}

      }
    end

    threads.each {|x| x.join}

    #Remove products with price less than or equals zero
    @found_products.reject! { |x| x.price <= 0.0 }

    Thread.new { save_data }

    @found_products.sort_by{|e| e[:price]}

  end

  def Search.save_data
    Thread.new{

      Search.where(search_word: @search_word).first_or_create

      Product.transaction do
      Product.where("search_word = ?", @search_word)
             .update_all(:status => false)
      @found_products.each(&:save)

      end
    }
  end

  def Search.update_prices
    searches = Search.all

    searches.each do |s|
      Thread.new { search_products s.search_word }
      #debugger
      sleep 15
    end

  end
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :category
  has_many :product
  validates :category, presence: true
  ratyrate_rateable "id"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :alert       
  ratyrate_rater

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  before_action :find_site, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new site_params

    if @site.save
      redirect_to @site, notice: "Site cadastrado com sucesso!"
    else
      render 'new', nocite: "Falha ao cadastrar Site!"
    end
  end

  def show
  end 

  def edit
  end

  def update
    if @site.update site_params
      redirect_to @site, notice: "Site alterado com sucesso!"
    else
      render 'edit'
    end
  end

  def destroy
    @site.destroy
    redirect_to sites_path
  end

  private

  def site_params
    params.require(:site).permit(:name, :link, :logo, :description, :category_id, :product_link_tag, :price_tag, :image_tag, :description_tag, :category_tag, :status)
  end

  def find_site
    @site = Site.find(params[:id])
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,style)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: style)
  end 

  def currency_format(number)
    number_to_currency number,
    unit: "R$",
    separator: ".",
    delimiter: ","
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
     toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pesquisa Web</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'jquery.blockUI' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id="main_navigation" class="clearfix">
    <div class="row">
    <div class="col-md-12">

      <%= link_to "Pesquisa Web", root_path, class: "name" %>
      <div class="col-md-6 col-lg-5 col-sm-4 hidden-sm">
        <div id="search_top" >
         <form action="#" method="get" id="form" class="form-horizontal">
              <div class="form-group">
                <div class="col-md-10 col-md-offset-2 col-lg-offset-4 col-lg-12 col-sm-offset-4 col-sm-12">
                  <input type="text" id="search_word2" required style="border: 2px solid white"/>
                  <button type="submit" value="" class="button" id="search" style="margin-left:4px; border: 2px solid white">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
            </div>
         </form>
       </div>
      </div>
     <div class="col-md-2 col-lg-3 col-sm-2 pull-right">
      <nav id="primary_nav_wrap" >

        <ul>
          <li style="display:none"><a href="/">Home</a></li>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to 'Administração', rails_admin_path %></li>
            <% end %>
            <li>
              <a href="#">Conta</a>
              <ul>
                <li><%= link_to gravatar_for(current_user, 'gravatar-small') + 'Perfil', user_profile_path %></li>
                <li><%= link_to 'Configurações', edit_user_registration_path %></li>
                <li><%= link_to 'Sair', destroy_user_session_path, :method => :delete%></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
  </div>
  </header>

  <%= yield %>

  <script type="text/javascript">
      <%= yield :js %>

      /* Friendly URL rewrite */
    $("#form").submit(function() {
        /* Remove unwanted characters, only accept alphanumeric and space */
        var keyword = $('#search_word2').val().replace(/[^A-Za-z0-9 ]/g,'');

        /* Replace multi spaces with a single space */
        keyword = keyword.replace(/\s{2,}/g,' ');

        /* Replace space with a '-' symbol */
        keyword = keyword.replace(/\s/g, "-");

        var cleanUrl = 'http://' + window.location.host + '/search/' + keyword.toLowerCase();
        window.location = cleanUrl;

        return false;  // Prevent default button behaviour
    });

     $(document).ready(function() {

        $('#search').click(function() {
            if(document.getElementById("search_word").value != "")
            {
              $.blockUI({ message: null });
            }
        });
    });

  </script>

  <footer id="main_footer">
      <p class="copyright">&copy;Pesquisa Web</p>
      <nav>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-facebook-official"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
      </nav>
  </footer>
  <%= render 'layouts/messages' %>
</body>
</html>